services:
  nethermind-gnosis:
    container_name: nethermind-gnosis
    build:
      context: .
      dockerfile: x64.Dockerfile
    restart: unless-stopped
    networks:
      - db_setup_backend 
    ports:
      - 30313:30303/tcp
      - 30313:30303/udp
      - 8515:8545
      - 8552:8551
    volumes:
      - .state/nethermind-gnosis:/data
      - .state/jwtsecret-gnosis/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      --config=gnosis
      --datadir=/data
      --log=INFO
      --Sync.SnapSync=true
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,Circles]
      --JsonRpc.JwtSecretFile=/jwt.hex
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Network.DiscoveryPort=30303
      --HealthChecks.Enabled=false
    # --Init.ChainSpecPath=/nethermind/chainspec/gnosis.json
    # --Sync.FastSync=true

    env_file:
      - .env
    environment:
      - V1_HUB_ADDRESS=0x29b9a7fBb8995b2423a71cC17cf9810798F6C543
      - V2_HUB_ADDRESS=0xc12C1E50ABB450d6205Ea2C3Fa861b3B834d13e8
      - V2_NAME_REGISTRY_ADDRESS=0xA27566fD89162cC3D40Cb59c87AAaA49B85F3474
      - V2_STANDARD_TREASURY_ADDRESS=0x08F90aB73A515308f03A718257ff9887ED330C6e
      - V2_ERC20_LIFT_ADDRESS=0x5F99a795dD2743C36D63511f0D4bc667e6d3cDB5
      - POSTGRES_CONNECTION_STRING=Server=192.168.2.110;Port=5432;Database=postgres;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - START_BLOCK=12000000
    logging:
      driver: "journald"

  consensus-gnosis:
    container_name: consensus-gnosis
    platform: linux/amd64
    image: sigp/lighthouse:v5.3.0-amd64-modern
    restart: always
    networks:
      - db_setup_backend 
    ports:
      - 9014:9000/tcp     # Changed to avoid conflict
      - 9014:9000/udp     # Changed to avoid conflict
      - 5058:5054/tcp     # Changed to avoid conflict
    expose:
      - 4000
    volumes:
      - .state/consensus-gnosis/data:/data
      - .state/jwtsecret-gnosis/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse
      beacon_node
      --network=gnosis
      --disable-upnp
      --datadir=/data
      --port=9000
      --http
      --http-address=0.0.0.0
      --http-port=4000
      --execution-endpoint=http://nethermind-gnosis:8551
      --execution-jwt=/jwt.hex
      --checkpoint-sync-url=https://checkpoint.gnosis.gateway.fm/
    logging:
      driver: "journald"

networks:
  db_setup_backend:
    external: true